In [6]:
import pandas as pd
import requests
import time

## Google map setup

Given google map link use google map api to get info on lat/lang or place names or something like that

## Google map data x API call integration

- convert google map lat/lang place names into station ids using /stations api and parameter with keyword or something

In [15]:
# Placeholder station IDs - later populate with Google Maps integration
# These are real IMO station IDs along/near Ring Road
station_ids = [
    1350,  # Keflavíkurflugvöllur (Reykjavík area)
    1475  # Reykjavík
    
]

weather_api = "https://api.vedur.is/weather"
url = f"{weather_api}/observations/aws/hour"

all_station_data = []

for station_id in station_ids:
    params = {
        "station_id": station_id,
        "parameters": "all",
        "format": "json",
        "day_from": "2026-08-03",
        "day_to": "2026-08-03",
    }
    
    try:
        result = requests.get(url, params=params, timeout=10)
        result.raise_for_status()
        data = result.json()
        
        if data:  # Only add if data returned
            # Add station_id to each record for traceability
            for record in data:
                record['station_id'] = station_id
            all_station_data.extend(data)
            print(f"✅ Station {station_id}: {len(data)} records")
        else:
            print(f"⚠️ Station {station_id}: No data returned")
            
    except requests.exceptions.RequestException as e:
        print(f"❌ Station {station_id}: Request failed - {e}")
    except Exception as e:
        print(f"❌ Station {station_id}: Error - {e}")

    time.sleep(2)  

print(f"\nTotal records collected: {len(all_station_data)}")


# Convert to DataFrame for inspection
df_weather = pd.DataFrame(all_station_data)
df_weather.head()

✅ Station 1350: 24 records
✅ Station 1475: 24 records

Total records collected: 48

,station,name,time,year,month,day,hour,t,tx,tn,...,radlwix,radlws,radlwsx,raduv,raduvx,rsun,ts,sal,count_measurements,station_id
0,1350,Keflavíkurflugvöllur,2026-08-03T00:00:00,2026,8,2,24,9.7,9.8,9.6,...,None,None,None,None,None,None,None,None,6,1350
1,1350,Keflavíkurflugvöllur,2026-08-03T01:00:00,2026,8,3,1,9.5,9.8,9.5,...,None,None,None,None,None,None,None,None,6,1350
2,1350,Keflavíkurflugvöllur,2026-08-03T02:00:00,2026,8,3,2,9.4,9.7,9.2,...,None,None,None,None,None,None,None,None,6,1350
3,1350,Keflavíkurflugvöllur,2026-08-03T03:00:00,2026,8,3,3,9.5,9.6,9.4,...,None,None,None,None,None,None,None,None,6,1350
4,1350,Keflavíkurflugvöllur,2026-08-03T04:00:00,2026,8,3,4,9.4,9.6,9.4,...,None,None,None,None,None,None,None,None,6,1350

In [16]:
# Inspect the data structure
print("Columns:", df_weather.columns.tolist())
print("\nShape:", df_weather.shape)
print("\nStation IDs found:", df_weather['station_id'].unique())
print("\nDate range:", df_weather['time'].min(), "to", df_weather['time'].max())
df_weather.head(10)

Columns: ['station', 'name', 'time', 'year', 'month', 'day', 'hour', 't', 'tx', 'tn', 'rh', 'vp', 'td', 'f', 'fx', 'fg', 'fgfx', 'd', 'd_txt', 'dsdev', 'ps', 'p', 'r', 'tg', 'tgn', 't0', 't0x', 't0n', 'tug5', 'tug10', 'tug15', 'tug20', 'tug50', 'tug100', 'radgl', 'radglx', 'radsc', 'radscx', 'radsws', 'radswsx', 'radlwi', 'radlwix', 'radlws', 'radlwsx', 'raduv', 'raduvx', 'rsun', 'ts', 'sal', 'count_measurements', 'station_id']

Shape: (48, 51)

Station IDs found: [1350 1475]

Date range: 2026-08-03T00:00:00 to 2026-08-03T23:00:00

,station,name,time,year,month,day,hour,t,tx,tn,...,radlwix,radlws,radlwsx,raduv,raduvx,rsun,ts,sal,count_measurements,station_id
0,1350,Keflavíkurflugvöllur,2026-08-03T00:00:00,2026,8,2,24,9.7,9.8,9.6,...,None,None,None,None,None,None,None,None,6,1350
1,1350,Keflavíkurflugvöllur,2026-08-03T01:00:00,2026,8,3,1,9.5,9.8,9.5,...,None,None,None,None,None,None,None,None,6,1350
2,1350,Keflavíkurflugvöllur,2026-08-03T02:00:00,2026,8,3,2,9.4,9.7,9.2,...,None,None,None,None,None,None,None,None,6,1350
3,1350,Keflavíkurflugvöllur,2026-08-03T03:00:00,2026,8,3,3,9.5,9.6,9.4,...,None,None,None,None,None,None,None,None,6,1350
4,1350,Keflavíkurflugvöllur,2026-08-03T04:00:00,2026,8,3,4,9.4,9.6,9.4,...,None,None,None,None,None,None,None,None,6,1350
5,1350,Keflavíkurflugvöllur,2026-08-03T05:00:00,2026,8,3,5,9.2,9.6,8.9,...,None,None,None,None,None,None,None,None,6,1350
6,1350,Keflavíkurflugvöllur,2026-08-03T06:00:00,2026,8,3,6,9.4,9.5,9.1,...,None,None,None,None,None,None,None,None,6,1350
7,1350,Keflavíkurflugvöllur,2026-08-03T07:00:00,2026,8,3,7,10.2,10.3,9.4,...,None,None,None,None,None,None,None,None,6,1350
8,1350,Keflavíkurflugvöllur,2026-08-03T08:00:00,2026,8,3,8,10.6,10.9,10.2,...,None,None,None,None,None,None,None,None,6,1350
9,1350,Keflavíkurflugvöllur,2026-08-03T09:00:00,2026,8,3,9,11.1,11.1,10.6,...,None,None,None,None,None,None,None,None,6,1350

In [17]:
# Save raw data for DuckDB pipeline
import os
os.makedirs("data", exist_ok=True)

df_weather.to_parquet("data/iceland_weather_raw.parquet", index=False)
df_weather.to_csv("data/iceland_weather_raw.csv", index=False)

print("Saved to data/iceland_weather_raw.parquet and .csv")
print(f"File size: {os.path.getsize('data/iceland_weather_raw.parquet') / 1024:.1f} KB")

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.